/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * PredictionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-05T17:40:11.794575+02:00[Europe/Paris]")
public class PredictionResponse {
  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PREDICTION = "prediction";
  @SerializedName(SERIALIZED_NAME_PREDICTION)
  private String prediction;

  public static final String SERIALIZED_NAME_PROBABILITIES = "probabilities";
  @SerializedName(SERIALIZED_NAME_PROBABILITIES)
  private Map<String, String> probabilities = null;


  public PredictionResponse path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Local path of the invoked predictive model
   * @return path
  **/
  @ApiModelProperty(required = true, value = "Local path of the invoked predictive model")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public PredictionResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Uuid of the prediction
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Uuid of the prediction")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public PredictionResponse prediction(String prediction) {
    
    this.prediction = prediction;
    return this;
  }

   /**
   * The prediction
   * @return prediction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The prediction")

  public String getPrediction() {
    return prediction;
  }


  public void setPrediction(String prediction) {
    this.prediction = prediction;
  }


  public PredictionResponse probabilities(Map<String, String> probabilities) {
    
    this.probabilities = probabilities;
    return this;
  }

  public PredictionResponse putProbabilitiesItem(String key, String probabilitiesItem) {
    if (this.probabilities == null) {
      this.probabilities = new HashMap<String, String>();
    }
    this.probabilities.put(key, probabilitiesItem);
    return this;
  }

   /**
   * Get probabilities
   * @return probabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getProbabilities() {
    return probabilities;
  }


  public void setProbabilities(Map<String, String> probabilities) {
    this.probabilities = probabilities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredictionResponse predictionResponse = (PredictionResponse) o;
    return Objects.equals(this.path, predictionResponse.path) &&
        Objects.equals(this.id, predictionResponse.id) &&
        Objects.equals(this.prediction, predictionResponse.prediction) &&
        Objects.equals(this.probabilities, predictionResponse.probabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, id, prediction, probabilities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredictionResponse {\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    probabilities: ").append(toIndentedString(probabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

